name: Charade You Are - Wazery's Personal Blog
description: Rails, Open Source, Sci-Fi, Ambient  Music
meta_description: 'Rails, Open Source, Sci-Fi, Ambient  Music'

markdown: redcarpet
highlighter: pygments
logo: true
paginate: 15
baseurl: /
domain_name: 'http://blog.wazery.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://blog.wazery.com'
author:         'Islam Wazery'

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Rakefile']
